### ISSUE TITLE
Temporary files not beeing removed after tests are completed (Jest, Windows)

### ISSUE THREAD

**Issue by armano2** [raszi/node-tmp#229] opened 2020-01-28 04:18 UTC
## Operating System
- [x] Linux
- [x] Windows 7
- [x] Windows 10
- [x] MacOS
- other: 

## NodeJS Version
- [x] 8.x
- [x] 10.x
- [x] 12.x
- [x] 13.x
- other: 

## Tmp Version
0.1.0 and master

## Expected Behavior
Temporary files should be removed after test is finishes

## Experienced Behavior
Temporary files are not removed

--------------------

I'm experiencing this issues within jest tests, this can be reproduced in 
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/tests/lib/persistentParse.ts
- https://github.com/conventional-changelog/commitlint

If needed i can prepare small repo project or create test scenario

**Comment by armano2** [comment] 2020-01-28 14:23
i did some digging and this seems to be issue with jest isolating tests
process events are not being triggered and cleanup is not triggered

**Comment by silkentrance** [comment] 2020-01-29 18:25
I will have a look at this.

**Comment by silkentrance** [comment] 2020-01-29 18:32
@armano2 Ah I see. Now, there was a change to the rmdirSync API which expects a second optional parameter. ATM we will pass the next handler to this function, too, which causes node fs rmdirSync to fail.

There is already a bug fix for that. Perhaps you can try out node-tmp/master?

I am currently working on stabilising the solution and getting the event handling stuff right. Hopefully @raszi will then make a new release :smile: 

Other than that: this should be a duplicate of #209

**Comment by silkentrance** [comment] 2020-01-29 18:32
Reopening, seeing that you already tried out master.

**Comment by silkentrance** [comment] 2020-01-29 19:20
I just tried this with the latest master and running the tests from your project.

Turns out that the temporary objects are cleaned up as expected.

However, the SIGINT handler will not be called on CTRL-C. But this is a different issue.

Can you please check this again with the latest master?

**Comment by silkentrance** [comment] 2020-01-29 19:34
There is a bug in current master on dirSync/removeCallback. (next is not a function.)

**Comment by silkentrance** [comment] 2020-01-29 20:18
@armano2 is this the issue that the SIGINT handler will not be called?

**Comment by armano2** [comment] 2020-01-29 20:20
yes, i did some debugging and it looks like `process.on` and `process.addEventListener` is not triggered at all

**Comment by silkentrance** [comment] 2020-01-29 22:02
@armano2 thank you.

I just did some debugging and by looking at the jest code, it seems that they actually switched over to worker threads. In the past, they would just import the test suite module and provide it with a more or less empty sandbox context. This lead to the fact that tmp got loaded multiple times, installing its listeners over and over again.

With the workers now in place, the test suite module will be loaded in the context of the so spawned worker thread and tmp will be loaded once per worker thread, no longer installing its listeners multiple times.

In order to test this, I added the import for tmp to jest-cli and put some debug output in the safe listener installer, logging the available listeners. It shows that the process object is different from the worker thread's process.

https://nodejs.org/api/worker_threads.html#worker_threads_class_worker

And ATM I do not see any way of making SIGINT handlers work in that scenario as these signals will not be passed to the worker thread.

**Comment by silkentrance** [comment] 2020-01-29 22:12
Here is a small diagram on how the process environment looks like and which handlers will be called

main process (standard SIGINT handler is used)
  -- worker thread (will be terminated as soon as the main process is interrupted, tmp exit handler will not be called)

**Comment by silkentrance** [comment] 2020-01-29 22:13
The only work around for this is to use inband testing alone.

**Comment by silkentrance** [comment] 2020-01-29 22:48
I dug somewhat deeper and the enableWorkerThreads option is not set, so jest is actually using child processes.

**Comment by silkentrance** [comment] 2020-01-29 22:51
Nah, it is basically the same as with the worker threads. SIGINT will be received by the main process and the child processes will just be terminated.
However, the exit handler should still be called during normal execution, similarly to our own tests.

**Comment by silkentrance** [comment] 2020-01-30 14:39
@armano2 I have found a solution to this, see the gist https://gist.github.com/silkentrance/f0e1ff1d689891e124e2a8b73bd31299

**Comment by silkentrance** [comment] 2020-01-30 14:40
Somehow all this runincontext stuff will break the process event listeners.

**Comment by armano2** [comment] 2020-01-30 15:55
thank you for investigating it, maybe you should consider adding this do readme

**Comment by silkentrance** [comment] 2020-01-30 20:11
@armano2 I an currently working on a package for doing exactly that. I will reference the package from the documentation. Got a little bit carried away, though :)

**Comment by silkentrance** [comment] 2020-01-30 20:12
@armano2 can we close this for now?

**Closed** 2020-01-30 20:17 UTC
Labels: bug, wontfix, workaround
