### ISSUE TITLE
Temp file with an extension

### ISSUE THREAD

**Issue by ktalebian** [raszi/node-tmp#201] opened 2019-11-05 18:07 UTC
How can I create a temp file with an extension?

**Comment by jamesmbourne** [comment] 2019-11-08 13:17
You can pass a `postfix` option e.g.

```js
const tmpobj = tmp.fileSync({ postfix: ".html" });
```

**Comment by silkentrance** [comment] 2019-11-15 15:21
Duplicate of #200

**Closed by silkentrance** 2019-11-15 15:21 UTC
Labels: question
